name: E2E on Chrome

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build and test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.8.1
      - run: npm ci
      - run: npm run format
      - run: npm run build

  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3
      # https://github.com/cypress-io/github-action
      - name: Test E2E
        uses: cypress-io/github-action@v4
        with:
          start: 'npx cypress run'
          wait-on: 'http://localhost:4200'
       
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
