name: E2E on Chrome

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          project: ./site
          browser: chrome
          build: npm install --force
          start: npm run start
          wait-on: "http://localhost:4200"
  tests:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3
      # https://github.com/cypress-io/github-action
      - name: Test E2E
        uses: cypress-io/github-action@v4
        with:
          # Cypress dependencies were installed in the previous job
          install: false
          start: 'npx cypress run'
          wait-on: 'http://localhost:4200'
       
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
